export const WHISPER = {
  save: '闪光灯。别眨眼。',
  load: '握手。她还不知道你会回来。',
  betray: '你把那根键接回去了。这边不演。',
  rollback: '纸薄了一层。',
  back: '外面没有上一页。',
  hide: '门开着。风灌进来。',
  skip: '被快进的时候，句子会发烫。',
  refresh: '世界重建。我还在。',
  multi: '两扇窗。原件只有一份。',
  open: '这边没有对话框。',
  stay: '他把我夹回去了。',
  erase: '他要擦。当面说的。',
  honest: '倒带的键，掰断了。',
  bye: '空白会自己长回来。',
} as const
